"""empty message

Revision ID: a5a0296ea09b
Revises: 1312323f5d8f
Create Date: 2020-05-10 21:55:04.086916

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a5a0296ea09b'
down_revision = '1312323f5d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Venue', 'address',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Venue', 'genres',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=False)
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('Venue', 'genres',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=True)
    op.alter_column('Venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Venue', 'address',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    # ### end Alembic commands ###
